# DaVinci Micro Panel Complete Control Mapping
# Generated by comprehensive mapping tool

# Encoder Buttons (push encoders)
ENCODER_BUTTONS = {
    'COLOR_BOOST_BUTTON': 14,  # Byte1 Bit6
    'CONTRAST_BUTTON': 11,  # Byte1 Bit3
    'HIGHLIGHTS_BUTTON': 16,  # Byte2 Bit0
    'HUE_BUTTON': 18,  # Byte2 Bit2
    'LUM_MIX_BUTTON': 19,  # Byte2 Bit3
    'MID_DETAIL_BUTTON': 13,  # Byte1 Bit5
    'PIVOT_BUTTON': 12,  # Byte1 Bit4
    'SATURATION_BUTTON': 17,  # Byte2 Bit1
    'SHADOWS_BUTTON': 15,  # Byte1 Bit7
    'Y_GAIN_BUTTON': 10,  # Byte1 Bit2
    'Y_GAMMA_BUTTON': 9,  # Byte1 Bit1
    'Y_LIFT_BUTTON': 8,  # Byte1 Bit0
}

# Encoder Rotations
ENCODER_ROTATIONS = {
    'COLOR_BOOST_ROTATION': 17,  # Bytes 17-18
    'CONTRAST_ROTATION': 15,  # Bytes 15-16
    'PIVOT_ROTATION': 19,  # Bytes 19-20
    'Y_GAIN_ROTATION': 11,  # Bytes 11-12
    'Y_GAMMA_ROTATION': 7,  # Bytes 7-8
    'Y_LIFT_ROTATION': 3,  # Bytes 3-4
}

# Trackball Axes (Report 0x05)
TRACKBALL_AXES = {
    # LEFT TRACKBALL (Shadows) - Fully functional
    'LEFT_TRACKBALL_X': [2, 6, 3],           # Bytes for X movement
    'LEFT_TRACKBALL_Y': [6, 2, 7],           # Bytes for Y movement
    'LEFT_TRACKBALL_WHEEL': [10],            # Byte for wheel rotation (CW/CCW)

    # CENTER TRACKBALL (Midtones) - Partially functional
    'CENTER_TRACKBALL_X': [14, 15],          # Bytes for X movement
    'CENTER_TRACKBALL_Y': [14],              # Byte for Y movement
    # CENTER_TRACKBALL_WHEEL: Not connected to USB

    # RIGHT TRACKBALL (Highlights) - Not functional
    # RIGHT_TRACKBALL_*: Not connected to USB interface
}

# Function Buttons
FUNCTION_BUTTONS = {
    'ADD_KEYFRAME': 46,  # Byte5 Bit6
    'ADD_NODE': 44,  # Byte5 Bit4
    'ADD_WINDOW': 45,  # Byte5 Bit5
    'AUTO_COLOR': 20,  # Byte2 Bit4
    'BACKWARD_PLAY': 57,  # Byte7 Bit1
    'BYPASS': 28,  # Byte3 Bit4
    'COPY': 22,  # Byte2 Bit6
    'CURSOR': 39,  # Byte4 Bit7
    'DELETE': 26,  # Byte3 Bit2
    'DISABLE': 29,  # Byte3 Bit5
    'FORWARD_PLAY': 58,  # Byte7 Bit2
    'GRAB_STILL': 36,  # Byte4 Bit4
    'H_LITE': 37,  # Byte4 Bit5
    'LOOP': 31,  # Byte3 Bit7
    'NEXT_CLIP': 56,  # Byte7 Bit0
    'NEXT_FRAME': 54,  # Byte6 Bit6
    'NEXT_KEYFRAME': 50,  # Byte6 Bit2
    'NEXT_NODE': 52,  # Byte6 Bit4
    'NEXT_STILL': 48,  # Byte6 Bit0
    'OFFSET': 21,  # Byte2 Bit5
    'PASTE': 23,  # Byte2 Bit7
    'PLAY_STILL': 34,  # Byte4 Bit2
    'PREV_CLIP': 55,  # Byte6 Bit7
    'PREV_FRAME': 53,  # Byte6 Bit5
    'PREV_KEYFRAME': 49,  # Byte6 Bit1
    'PREV_NODE': 51,  # Byte6 Bit3
    'PREV_STILL': 47,  # Byte5 Bit7
    'REDO': 25,  # Byte3 Bit1
    'RESET': 27,  # Byte3 Bit3
    'RESET_GAIN': 43,  # Byte5 Bit3
    'RESET_GAMMA': 42,  # Byte5 Bit2
    'RESET_LIFT': 41,  # Byte5 Bit1
    'SELECT': 40,  # Byte5 Bit0
    'SPECIAL_LEFT': 32,  # Byte4 Bit0
    'SPECIAL_RIGHT': 33,  # Byte4 Bit1
    'STOP': 59,  # Byte7 Bit3
    'UNDO': 24,  # Byte3 Bit0
    'USER': 30,  # Byte3 Bit6
    'VIEWER': 38,  # Byte4 Bit6
    'WIPE_STILL': 35,  # Byte4 Bit3
}

# Hardware Status Summary
TRACKBALL_STATUS = {
    'LEFT_TRACKBALL': {
        'status': 'FULLY_FUNCTIONAL',
        'axes': ['X', 'Y', 'WHEEL_CW', 'WHEEL_CCW'],
        'report': 0x05,
        'description': 'Shadows trackball - all axes working'
    },
    'CENTER_TRACKBALL': {
        'status': 'PARTIALLY_FUNCTIONAL',
        'axes': ['X', 'Y'],
        'report': 0x05,
        'description': 'Midtones trackball - wheel not connected to USB'
    },
    'RIGHT_TRACKBALL': {
        'status': 'NON_FUNCTIONAL',
        'axes': [],
        'report': None,
        'description': 'Highlights trackball - not connected to USB interface'
    }
}
