name: micro-panel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - requests>=2.28.0
  - psutil>=5.9.0

  # GUI dependencies
  - pyqt=5

  # Development tools
  - pytest>=7.0.0
  - black>=22.0.0
  - isort>=5.10.0
  - flake8>=5.0.0

  # System/hardware interface
  - pyudev>=0.24.0

    # Pip-only dependencies (not available in conda)
  - pip:
      - hidapi>=0.12.0
      - pynput>=1.7.6
      - python-rtmidi>=1.4.9
      - mido>=1.3.0
      - websocket-client>=1.4.0
      - keyboard>=0.13.5
