# DaVinci Micro Panel Control Mapping
# Generated by robust mapping tool
# Includes error handling and reconnection logic

BUTTON_MAP = {
    8: 'Y_LIFT_BUTTON',  # Byte1 Bit0
    20: 'SHOT_COLOR',  # Byte2 Bit4
    22: 'COPY',  # Byte2 Bit6
    23: 'PASTE',  # Byte2 Bit7
    55: 'PREV',  # Byte6 Bit7
    56: 'NEXT',  # Byte7 Bit0
}

MOVEMENT_MAP = {
    1: 'Y_LIFT_BUTTON_bytes_1_2',  # Bytes 1-2
    3: 'Y_LIFT_BUTTON_bytes_3_4',  # Bytes 3-4
}
