# DaVinci Micro Panel Detailed Trackball Mapping
# Generated by detailed trackball mapping tool

TRACKBALL_PATTERNS = {
    'LEFT_TRACKBALL_X': {'bytes': [2, 6, 3], 'events': 160},
    'LEFT_TRACKBALL_Y': {'bytes': [6, 2, 7], 'events': 161},
    'LEFT_TRACKBALL_WHEEL_CW': {'bytes': [10], 'events': 552},
    'LEFT_TRACKBALL_WHEEL_CCW': {'bytes': [10], 'events': 542},
    'CENTER_TRACKBALL_X': {'bytes': [14, 15], 'events': 151},
    'CENTER_TRACKBALL_Y': {'bytes': [14], 'events': 158},
}

# Detailed byte patterns for each axis
DETAILED_PATTERNS = {
    'LEFT_TRACKBALL_X': {
        2: {'min': 0, 'max': 240, 'unique': 16},
        3: {'min': 0, 'max': 255, 'unique': 11},
        4: {'min': 0, 'max': 255, 'unique': 2},
        6: {'min': 0, 'max': 224, 'unique': 15},
        7: {'min': 0, 'max': 255, 'unique': 2},
        8: {'min': 0, 'max': 255, 'unique': 2},
    },
    'LEFT_TRACKBALL_Y': {
        2: {'min': 0, 'max': 240, 'unique': 15},
        3: {'min': 0, 'max': 255, 'unique': 4},
        4: {'min': 0, 'max': 255, 'unique': 2},
        6: {'min': 0, 'max': 240, 'unique': 16},
        7: {'min': 0, 'max': 255, 'unique': 8},
        8: {'min': 0, 'max': 255, 'unique': 2},
    },
    'LEFT_TRACKBALL_WHEEL_CW': {
        2: {'min': 0, 'max': 192, 'unique': 3},
        3: {'min': 0, 'max': 255, 'unique': 2},
        4: {'min': 0, 'max': 255, 'unique': 2},
        6: {'min': 0, 'max': 96, 'unique': 2},
        7: {'min': 0, 'max': 59, 'unique': 2},
        10: {'min': 0, 'max': 240, 'unique': 10},
        11: {'min': 0, 'max': 255, 'unique': 2},
        12: {'min': 0, 'max': 255, 'unique': 2},
    },
    'LEFT_TRACKBALL_WHEEL_CCW': {
        10: {'min': 0, 'max': 240, 'unique': 10},
        11: {'min': 0, 'max': 255, 'unique': 3},
        12: {'min': 0, 'max': 255, 'unique': 2},
    },
    'CENTER_TRACKBALL_X': {
        10: {'min': 0, 'max': 192, 'unique': 3},
        11: {'min': 0, 'max': 255, 'unique': 3},
        12: {'min': 0, 'max': 255, 'unique': 2},
        14: {'min': 0, 'max': 240, 'unique': 16},
        15: {'min': 0, 'max': 255, 'unique': 11},
    },
    'CENTER_TRACKBALL_Y': {
        14: {'min': 0, 'max': 240, 'unique': 15},
        15: {'min': 0, 'max': 255, 'unique': 5},
    },
    'CENTER_TRACKBALL_WHEEL_CW': {
        14: {'min': 0, 'max': 64, 'unique': 2},
    },
    'CENTER_TRACKBALL_WHEEL_CCW': {
    },
    'RIGHT_TRACKBALL_X': {
    },
    'RIGHT_TRACKBALL_Y': {
    },
    'RIGHT_TRACKBALL_WHEEL_CW': {
    },
    'RIGHT_TRACKBALL_WHEEL_CCW': {
    },
}
